var date = function (val, type, doc) {
		if (val instanceof Date) {
				return moment(val).format("MM/DD/YYYY");
		} else {
				return;
		}
};

Meteor.methods({
	exportEnrollments: function () {
		var user = Meteor
						.users
						.findOne({
								"_id": this.userId
						}, {
								fields: {
										"profile": 1,
										"roles": 1
								}
						});
				var getUserCompany = user.profile.company;
				var getUserBranch = user.profile.branch;
				var getUserRoles = user.roles;

				var userRoles = function (user) {

						if (Roles.userHasRole(user._id, 'admin')) {
								return {};
						} else if (Roles.userHasRole(user._id, 'HQ')) {
								return {company: user.profile.company};
						} else if (Roles.userHasRole(user._id, 'Branch')) {
								return {createdBy: user._id};
						} else if (Roles.userHasRole(user._id, 'insurer')) {
								return {insurer: user.profile.insurer[0]};
						} else 
								return "Error";
						}
				;

				var exportLimit = userRoles(user);

				var delimiter = ";";

				var fields = [
						"dateEnrolled",
						"fullName",
						"birthDate",
						"ageOfEnrollee",
						"maritalStatus",
						"gender",
						"spouseName",
						"spouseBirthdate",
						"spouseAge",
						"spouseMaritalStatus",
						"spouseGender",
						"childrenName",
						"childrenBirthdate",
						"childrenAge",
						"childrenMaritalStatus",
						"childrenGender",
						"children2Name",
						"children2Birthdate",
						"children2Age",
						"children2MaritalStatus",
						"children2Gender",
						"children3Name",
						"children3Birthdate",
						"children3Age",
						"children3MaritalStatus",
						"children3Gender",
						"children4Name",
						"children4Birthdate",
						"childrenA4ge",
						"children4MaritalStatus",
						"children4Gender",
						"children5Name",
						"children5Birthdate",
						"childrenA5ge",
						"children5MaritalStatus",
						"children5Gender",
						"children6Name",
						"children6Birthdate",
						"children6Age",
						"children6MaritalStatus",
						"children6Gender",
						"children7Name",
						"children7Birthdate",
						"children7Age",
						"children7MaritalStatus",
						"children7Gender",
						"children8Name",
						"children8Birthdate",
						"children8Age",
						"children8MaritalStatus",
						"children8Gender",
						"children9Name",
						"children9Birthdate",
						"children9Age",
						"children9MaritalStatus",
						"children9Gender",
						"children10Name",
						"children10Birthdate",
						"children10Age",
						"children10MaritalStatus",
						"children10Gender",
						"parentName",
						"parentBirthdate",
						"parentAge",
						"parentMaritalStatus",
						"parentGender",
						"parent2Name",
						"parent2Birthdate",
						"parent2Age",
						"parent2MaritalStatus",
						"parent2Gender",
						"siblingName",
						"siblingBirthdate",
						"siblingAge",
						"siblingMaritalStatus",
						"siblingGender",
						"sibling2Name",
						"sibling2Birthdate",
						"sibling2Age",
						"sibling2MaritalStatus",
						"sibling2Gender",
						"sibling3Name",
						"sibling3Birthdate",
						"sibling3Age",
						"sibling3MaritalStatus",
						"sibling3Gender",
						"sibling4Name",
						"sibling4Birthdate",
						"sibling4Age",
						"sibling4MaritalStatus",
						"sibling4Gender",
						"sibling5Name",
						"sibling5Birthdate",
						"sibling5Age",
						"sibling5MaritalStatus",
						"sibling5Gender",
						"sibling6Name",
						"sibling6Birthdate",
						"sibling6Age",
						"sibling6MaritalStatus",
						"sibling6Gender",
						"sibling7Name",
						"sibling7Birthdate",
						"sibling7Age",
						"sibling7MaritalStatus",
						"sibling7Gender",
						"sibling8Name",
						"sibling8Birthdate",
						"sibling8Age",
						"sibling8MaritalStatus",
						"sibling8Gender",
						"sibling9Name",
						"sibling9Birthdate",
						"sibling9Age",
						"sibling9MaritalStatus",
						"sibling9Gender",
						"sibling10Name",
						"sibling10Birthdate",
						"sibling10Age",
						"sibling10MaritalStatus",
						"sibling10Gender",
						"maturityDate",
						"maturityDate1",
						"maturityDate2",
						"maturityDate3",
						"maturityDate4",
						"maturityDate5",
						"maturityDate6",
						"maturityDate7",
						"maturityDate8",
						"maturityDate9",
				];

				var data = [];

				var enrollment = Enrollments
						.find(exportLimit)
						.fetch();

				_.each(enrollment, function (c) {
						data.push([
								date(c.dateEnrolled),
								c.fullName,
								date(c.birthDate),
								c.ageOfEnrollee,
								c.maritalStatus,
								c.gender,
								c.spouseName,
								date(c.spouseBirthdate),
								c.spouseAge,
								c.spouseMaritalStatus,
								c.spouseGender,
								c.childrenName,
								date(c.childrenBirthdate),
								c.childrenAge,
								c.childrenMaritalStatus,
								c.childrenGender,
								c.children2Name,
								date(c.children2Birthdate),
								c.children2Age,
								c.children2MaritalStatus,
								c.children2Gender,
								c.children3Name,
								date(c.children3Birthdate),
								c.children3Age,
								c.children3aritalStatus,
								c.children3Gender,
								c.children4Name,
								date(c.children4Birthdate),
								c.children4Age,
								c.children4MaritalStatus,
								c.children4Gender,
								c.children5Name,
								date(c.children5Birthdate),
								c.children5Age,
								c.children5MaritalStatus,
								c.children5Gender,
								c.children6Name,
								date(c.children6Birthdate),
								c.children6Age,
								c.children6MaritalStatus,
								c.children6Gender,
								c.children7Name,
								date(c.children7Birthdate),
								c.children7Age,
								c.children7MaritalStatus,
								c.children7Gender,
								c.children8Name,
								date(c.children8Birthdate),
								c.children8Age,
								c.children8MaritalStatus,
								c.children8Gender,
								c.children9Name,
								date(c.children9Birthdate),
								c.children9Age,
								c.children9MaritalStatus,
								c.children9Gender,
								c.children10Name,
								date(c.children10Birthdate),
								c.children10Age,
								c.children10MaritalStatus,
								c.children10Gender,
								c.parentName,
								date(c.parentBirthdate),
								c.parentAge,
								c.parentMaritalStatus,
								c.parentGender,
								c.parent2Name,
								date(c.parent2Birthdate),
								c.parent2Age,
								c.parent2MaritalStatus,
								c.parent2Gender,
								c.siblingName,
								date(c.siblingBirthdate),
								c.siblingAge,
								c.siblingMaritalStatus,
								c.siblingGender,
								c.sibling2Name,
								date(c.sibling2Birthdate),
								c.sibling2Age,
								c.sibling2MaritalStatus,
								c.sibling2Gender,
								c.sibling3Name,
								date(c.sibling3Birthdate),
								c.sibling3Age,
								c.sibling3MaritalStatus,
								c.sibling3Gender,
								c.sibling4Name,
								date(c.sibling4Birthdate),
								c.sibling4Age,
								c.sibling4MaritalStatus,
								c.sibling4Gender,
								c.sibling5Name,
								date(c.sibling5Birthdate),
								c.sibling5Age,
								c.sibling5MaritalStatus,
								c.sibling5Gender,
								c.sibling6Name,
								date(c.sibling6Birthdate),
								c.sibling6Age,
								c.sibling6MaritalStatus,
								c.sibling6Gender,
								c.sibling7Name,
								date(c.sibling7Birthdate),
								c.sibling7Age,
								c.sibling7MaritalStatus,
								c.sibling7Gender,
								c.sibling8Name,
								date(c.sibling8Birthdate),
								c.sibling8Age,
								c.sibling8MaritalStatus,
								c.sibling8Gender,
								c.sibling9Name,
								date(c.sibling9Birthdate),
								c.sibling9Age,
								c.sibling9MaritalStatus,
								c.sibling9Gender,
								c.sibling10Name,
								date(c.sibling10Birthdate),
								c.sibling10Age,
								c.sibling10MaritalStatus,
								c.sibling10Gender,
								date(c.maturityDate),
								date(c.maturityDate1),
								date(c.maturityDate2),
								date(c.maturityDate3),
								date(c.maturityDate4),
								date(c.maturityDate5),
								date(c.maturityDate6),
								date(c.maturityDate7),
								date(c.maturityDate8),
								date(c.maturityDate9),
						]);
				});

				return {fields: fields, data: data, delimiter: delimiter};

		}
});